version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
      - custom_network

  redis:
    image: "redis:alpine"
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
